---
# tasks file for snmp

- name: install snmpd
  ansible.builtin.package:
    name: snmpd
    state: present

- name: optionally - set snmpd.conf to defaults
  ansible.builtin.copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: '0600'
    backup: yes
  when: snmpd_config_defaults == 'yes'

- name: configure snmpd
  ansible.builtin.lineinfile:
    dest: /etc/snmp/snmpd.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    backrefs: yes
    backup: no
    state: present
  with_items:
    - { regexp: '^(sysLocation ).*$', line: '\g<1>{{ snmp_location }}' }
    - { regexp: '^(sysContact ).*$', line: '\g<1>{{ snmp_contact }}' }
    - { regexp: '^(agentaddress ).*$', line: '\g<1>{{ snmp_agentaddress }}' }
    - { regexp: '^(com2sec.*public)(.*)$', line: '\g<1> {{ snmp_rocommunity }}' }
    - { regexp: '^(rocommunity )(.*public)(.*)$', line: '\g<1>{{ snmp_rocommunity }} {{ snmp_source }}' }
    - { regexp: '^(rocommunity)([ ].*? )(.*)$', line: '\g<1> {{ snmp_rocommunity }} {{ snmp_source }}' }
    - { regexp: '^(rocommunity6 )(.*public)(.*)$', line: '\g<1>{{ snmp_rocommunity }} {{ snmp_source }}' }
    - { regexp: '^(rocommunity6)([ ].*? )(.*)$', line: '\g<1> {{ snmp_rocommunity }} {{ snmp_source }}' }
    - { regexp: '^(# createuser .*)$', line: 'createuser {{ snmp_v3user }} SHA-512 {{ snmp_v3authpass }} AES {{ snmp_v3privpass }}' }
    - { regexp: '^(createuser )(.*{{ snmp_v3user }}).*$', line: 'createuser {{ snmp_v3user }} SHA-512 {{ snmp_v3authpass }} AES {{ snmp_v3privpass }}' }
    - { regexp: '^(rouser )(.*authPrivUser).*$', line: '\g<1>{{ snmp_v3user }} authpriv' }
    - { regexp: '^(rouser )(.*{{ snmp_v3user }}).*$', line: '\g<1>{{ snmp_v3user }} authpriv' }
  notify: "Restart snmpd"
