---
# tasks file for snmp

- name: install snmpd
  ansible.builtin.package:
    name: snmpd
    state: present

- name: optionally - set snmpd.conf to defaults
  ansible.builtin.copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: '0600'
    backup: yes
  when: snmpd_config_defaults == 'yes'

- name: configure snmpd
  ansible.builtin.lineinfile:
    dest: /etc/snmp/snmpd.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    backrefs: yes
    backup: no
    state: present
  with_items:
    - { regexp: '^(sysLocation ).*$', line: '\g<1>{{ snmp_location }}' }
    - { regexp: '^(sysContact ).*$', line: '\g<1>{{ snmp_contact }}' }
    - { regexp: '^(agentaddress ).*$', line: '\g<1>{{ snmp_agentaddress }}' }
    - { regexp: '^(rocommunity )(.*public)(.*)$', line: '\g<1>{{ snmp_rocommunity }}\g<3>' }
    - { regexp: '^(rocommunity6 )(.*public)(.*)$', line: '\g<1>{{ snmp_rocommunity }}\g<3>' }
    - { regexp: '^(rouser )(.*authPrivUser).*$', line: '\g<1>{{ snmp_v3user }}" authpriv -V systemonly"' }
  notify: "Restart snmpd"
